export enum IconTypes {
  step1 = "step1",
  step2 = "step2",
  step3 = "step3",
  step4 = "step4",
  step5 = "step5",
  file = "file",
  chevron = "chevron",
  qiwi = "qiwi",
  yandex = "yandex",
  webMoney = "webMoney",
  mail = "mail",
  vk = "vk",
  logo = "logo",
  burger = "burger",
  close = "close",
}
